#!/bin/bash

# Script that sets environment variables required to run custom Arbor installation

# check if PATH exists and set environment variable accordingly
if [[ ! -v PATH ]]; then
	export PATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/bin)
else
	export PATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/bin):$PATH
fi

# check if LD_LIBRARY_PATH exists and set environment variable accordingly
if [[ ! -v LD_LIBRARY_PATH ]]; then
	export LD_LIBRARY_PATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/lib)
else
	export LD_LIBRARY_PATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/lib):$LD_LIBRARY_PATH
fi

# check if PYTHONPATH exists and set environment variable accordingly
if [[ ! -v PYTHONPATH ]]; then
	export PYTHONPATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/lib/python3.8/site-packages) # or: .../python3.6/..., etc.
else
	export PYTHONPATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd/lib/python3.8/site-packages):$PYTHONPATH # or: .../python3.6/..., etc.
fi

# set CMAKE_PREFIX_PATH environment variable
export CMAKE_PREFIX_PATH=$(readlink -f ~/arbor_v0.9.1dev-xd-bugfix-simd)
